### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by jarutis** [andfanilo/streamlit-drawable-canvas-demo#1]
StreamlitAPIException: Method beta_color_picker() does not exist for st.sidebar. Did you mean st.beta_color_picker()?

```
Traceback:
File "/app/streamlit-drawable-canvas-demo/app.py", line 19, in <module>
    stroke_color = st.sidebar.beta_color_picker("Stroke color hex: ")
```

**Comment by andfanilo** [comment]
Hey @jarutis, thanks for reporting, I'll look into it!

**Comment by andfanilo** [comment]
Looks like color_picker is out of beta, this is fixed now :)
